name: Terraform Plan and Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    env:
      TF_WORKSPACE: default
      TF_VAR_example_variable: example_value # Replace with your environment variables

    permissions:
      id-token: write
      contents: read
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Replace with your desired version

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Plan
        id: terraform_plan
        run: terraform plan -out=tfplan
        env:
          # Set any necessary Terraform variables
          TF_VAR_example: example_value

      - name: Save Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan

      - name: Await Manual Approval
        uses: hmarr/auto-approve-action@v2 # Handles manual approval
        with:
          reactions: 👍👎
          approve_label: 'approved'
          reject_label: 'rejected'

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: ./artifact

      - name: Run Terraform Apply
        if: github.event.pull_request.merged == true # Approval linked to PR Merge to Main
        id:
          artifact: plan_overview
        command: Artifact-summary
