name: Example Terraform Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  call-terraform-workflow:
    uses: ./.github/workflows/newterraform.yml
    with:
      approvers: 'adig'
      app-env: 'prod'
      environment: 'production'
      infra-repo: ${{ github.repository }}
      infra-ref: ${{ github.ref }}
      terraform-version: '1.9.5'
      terraform-environment-dir: 'envs'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      GITHUB_PAT: ${{ github.token }}
    # You can also simply set
    # secrets: inherit