name: Terraform Plan and Apply

on:
  workflow_dispatch: # Triggered manually or on push to main branch
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Replace with your desired Terraform version

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Plan
        id: terraform_plan
        run: terraform plan -out=tfplan

      - name: Save Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan

      - name: Await Manual Approval
        uses: chrnorm/deploy-approval@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          timeout-minutes: 60 # Optional timeout for approval

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: .

      - name: Run Terraform Apply
        run: terraform apply tfplan
