name: Terraform Plan and Apply

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  terraform-plan:
    name: Run Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Plan
        id: terraform_plan
        run: terraform plan -out=tfplan

      - name: Save Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan

  terraform-apply:
    name: Run Terraform Apply
    needs: terraform-plan # Ensures this job runs only after the plan job
    runs-on: ubuntu-latest

    steps:
      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: .

      - name: Await Manual Approval
        run: echo "Awaiting manual approval"
        timeout-minutes: 60 # Optional: workflow will time out if not approved

      - name: Apply Terraform Plan
        run: terraform apply tfplan
